export enum Routes {
  Homepage = '/',
  Onboarding = '/onboarding',
  DreamList = '/onboarding/dreams',
  Introduction = '/onboarding/introduction',
  Montly_Payments = '/onboarding/monthly-payments',
  Annual_Payments = '/onboarding/annual-payments',
  Summary = '/onboarding/summary',
  NewDream = '/dream/new',
  DreamDetail = '/dream/detail',
  Emergency_intro = '/onboarding/emergency-fund',
  WeeklyReview = '/weekly-review',
  Emergency_add = '/onboarding/emergency-fund/add',
  Dashboard = '/dashboard',
  MonthlyReview = '/monthly-review',
}
